### ISSUE TITLE
Object/Field Schema Imports with Namespace

### ISSUE THREAD

**Issue by cnaccio** [salesforce/lwc-test#16]
We're currently building a managed package using LWC, and running into an issue with lwc-jest not including our namespace for schema imports. 

Example:

When importing the custom account field below...

`import AccountField from '@salesforce/schema/Project__c.Account__c';`

We get AccountField.fieldApiName == 'namespace__Account__c' within the application

However, within tests, the namespace isn't being provided and so AccountField.fieldApiName == 'Account__c' which is causing all kinds of issues as you could imagine.

Is this a bug/oversight, or is our approach incorrect? Any insight would be super helpful; thanks guys!

**Comment by pmdartus** [comment]
The current transforms in tests are ignorant from the namespace, it just parses the import identifier and returns the value: https://github.com/salesforce/lwc-test/blob/master/packages/%40lwc/jest-transformer/src/transforms/schema-scoped-import.js#L21-L28

In the code above, you can see that the transforms generate a generic return value but also a require statement. So instead of using the generic return value, you can mock the import to return the namespaced value. Here is an example using [`jest.mock`](https://jestjs.io/docs/en/jest-object#jestmockmodulename-factory-options)

```js
jest.mock('@salesforce/schema/Project__c.Account__c', () => {
  return {
    objectApiName: 'namespace__Project__c', 
    fieldApiName: 'namespace__Account__c'
  }
});
```

That being said, I think it worth exploring the capability to configure an override for the default namespace value at the `@lwc/jest-preset` level.

**Comment by cnaccio** [comment]
Ah perfect; this will work much better than the temp solution we had put
together. I def think at least an example/recipe would be good for ISV
partners building managed packages.

Thanks for the insight!
Charles Naccio
*Founder*
p:(855) 550-0606
m:(214) 305-8684
w:www.billable.io

**Comment by trevor-bliss** [comment]
@cnaccio We have some examples of mocking out `@salesforce/apex` in `lwc-recipes`, which is a different import but the same technique to override the default behavior:

https://github.com/trailheadapps/lwc-recipes/blob/68cd0e78fb1f2789fffc07377eb9e0f0c0aeee56/force-app/main/default/lwc/apexImperativeMethod/__tests__/apexImperativeMethod.test.js#L6

I agree it would be good to have more explicit doc/examples around this. Let me follow up with the doc team on that.

**Comment by cnaccio** [comment]
Ah ok this makes sense. Thanks for your help!
Charles Naccio
*Founder*
p:(855) 550-0606
m:(214) 305-8684
w:www.billable.io

**Comment by pmdartus** [comment]
Closing this issue for now due to lack of traction.

**Comment by Vignesh-Duraipandian** [comment]
aa

**Comment by Vignesh-Duraipandian** [comment]
LWC1504: Invalid module id""for type "schema". Explicit use of namespace "...(namespace)" in file "lwc.js" is prohibited. Use default namespace "c" instead.: Source. in managed package lwc component importing Schema class and fields getting error.  tried importing with managed package namespace.
