### ISSUE TITLE
Support for LWC npm module resolution

### ISSUE THREAD

**Issue by muenzpraeger** [salesforce/lwc-test#73]
The current version of LWC Test does not resolve 3rd party modules that are installed via npm.

The new module resolution for LWC has landed in v1.4.0, based on [this RFC](https://rfcs.lwc.dev/rfcs/lwc/0020-module-resolution). To support testing with imported modules the resolver package needs to implement the new mechanism.

**Comment by ekashida** [comment]
We discussed this as a team and agreed that 1) lwc-test should not have a hard dependency on lwc and 2) it goes against the testing model that we've been promoting where developers should stub out component dependencies instead of pulling in the actual components.

I'm sure you're already aware but for posterity's sake: you can use `@lwc/module-resolver` in a [defaultResolver](https://jestjs.io/docs/en/configuration#resolver-string) to accomplish this if you insist on testing against real dependencies.

**Comment by muenzpraeger** [comment]
I ran into this again. But this time not with the need to resolve npm modules for tests.

Instead I have a monorepo with different packages, where the current mechanism doesn't resolve modules in the same package.

Example:
`packages/@whatever/package/src/modules/my/card` has a dependency on `packages/@whatever/package/src/modules/my/button`. When I run the test for `my/card` the resolver does not resolve `my/button`

Is it still the same recommendation to write my own resolver? @ekashida @diervo @trevor-bliss

**Comment by pmdartus** [comment]
If the packages are from the same namespace, the `lwc-test` should take care of resolving the different for you IMO. @muenzpraeger Do you have a repro example for us to investigate?
